@startuml

start
:Запуск игры;
:Генерация лабиринта;
:Спавн игрока и Крота;

repeat
  :Игровой цикл;

  fork
    :Игрок управляет персонажем;
    if (Коллизия с ключом?) then (Да)
      :Собрать ключ;
      :Обновить счетчик ключей;
    endif

    if (Коллизия с дырой?) then (Да)
      :Активировать телепортацию;
      :Перенести игрока в случайную дыру;
    endif

    if (Все ключи собраны?) then (Да)
      :Разблокировать дверь;
    endif

    if (Взаимодействие с дверью?) then (Да)
      if (Дверь разблокирована?) then (Да)
        :Победа;
      else (Нет)
        :Сообщение "Соберите все ключи!";
      endif
    endif
  fork again
    :Крот (ИИ) обновляет позицию;
    if (Коллизия с игроком?) then (Да)
      :Поражение;
    endif
  end fork

repeat while (Игра продолжается?) is (Нет)
stop

:Сохранение рекорда;
:Показать таблицу рекордов;
end

@enduml