
BASE_SIZE = 5

CELL_WIDTH = 30
CELL_HEIGHT = 30

SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 1000
W_SHIFT = SCREEN_WIDTH // 2
H_SHIFT = SCREEN_HEIGHT // 2

PLAYER_SPEED = 50
PLAYER_WIDTH = CELL_WIDTH // 5
PLAYER_HEIGHT = CELL_HEIGHT // 4

ENEMY_SPEED = 75
ENEMY_WIDTH = CELL_WIDTH // 3
ENEMY_HEIGHT = CELL_HEIGHT // 3


CAST_COOLDOWN = 0

MAZE_SIZE = 7
WALL_PERCENT = 25

KEYS_NUMBER = 3
KEY_WIDTH = CELL_WIDTH // 4
KEY_HEIGHT = CELL_HEIGHT // 4

GATES_WIDTH = CELL_WIDTH // 2
GATES_HEIGHT = CELL_HEIGHT // 7

HOLES_NUMBER = 3
HOLE_WIDTH = CELL_WIDTH // 4
HOLE_HEIGHT = CELL_HEIGHT // 4

CAMERA_WIDTH = 0 #CELL_WIDTH // 6
CAMERA_HEIGHT =0 #CELL_HEIGHT // 6

RAYS_NUMBER = 16

COLOR_WHITE = (255, 255, 255)
COLOR_BLACK = (0, 0, 0)
COLOR_BROWN = (88, 57, 79)
COLOR_YELLOW = (255, 210, 0)
COLOR_PURPLE = (128, 0, 128)
COLOR_RED = (255, 0, 0)
COLOR_BLUE = (0, 0, 255)
COLOR_VIOLET = (191, 5, 247)

FRAME_DURATION = 0.1

IS_TRAINING = False